title: Save Democracy Indivisible North Inland
description: Community action for democracy, freedom, and the rule of law
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

header_pages:
  - about.md
  - events.md
  - join.md
  - gallery.md
  - resources.md

minima:
  social_links:
    - title: Gmail
      icon: email
      url: "mailto:sdini.org@gmail.com"
