organization_name: Save Democracy Indivisible North Inland
tagline: Democracy, rule of law, civil rights, peaceful civic action
email: info@sdini.org
instagram: ""
facebook: https://www.facebook.com/groups/savedemocracyindivisible/
bluesky: https://bsky.app/profile/savedemindivisible.bsky.social
